<template>
  <div class="main-content">
    <span>Olá, mundo!</span>
    <h1>Marcos Cantarutti</h1>
    <p>Desenvolvedor Web JR | VueJS | PHP</p>
  </div>

  <div>
    <ul class="social-container">
      <li class="social-item">
        <a href="https://www.linkedin.com/in/marcos-cantarutti/" target="_blank"><i class="bi bi-linkedin"></i></a>
      </li>
      <li class="social-item">
        <a href="mailto: marcossandim21@gmail.com" target="_blank"><i class="bi bi-envelope"></i></a>
      </li>
      <li class="social-item">
        <a href="https://twitter.com/LakaNegro21" target="_blank"><i class="bi bi-twitter"></i></a>
      </li>
      <li class="social-item">
        <a href="https://github.com/MarcosCantarutti" target="_blank">
          <i class="bi bi-github"></i>
        </a>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: "HomeView",
  components: {},
};
</script>
<style scoped>
.main-content {
  color: #fff;
  display: flex;
  align-items: center;
  flex-direction: column;
  margin: 0 auto;
  padding: 10rem;
}

.main-content span {
  -webkit-animation: scale-up-center 0.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: scale-up-center 0.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

.main-content h1 {
  font-size: 5rem;
  -webkit-animation: scale-up-center 1s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: scale-up-center 1s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

.main-content p {
  font-size: 1.5rem;
  color: #adadad;
  -webkit-animation: scale-up-center 1.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: scale-up-center 1.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

.social-container {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 3rem;
  color: #fff;
  margin: 0 auto;
  padding: 5rem;
}

.social-item {
  font-size: 2rem;
  text-align: center;
}

.social-item:hover {
  animation: pulse 1s infinite;
}

.social-item a {
  color: #fff;
  transition: 0.3s all;
}

.social-item a:hover {
  color: rgb(158, 156, 156);
}

@keyframes pulse {
  from {
    transform: scale(1);
    opacity: 1;
  }

  50% {
    transform: scale(0.75);
    opacity: 0.25;
  }

  to {
    transform: scale(1);
    opacity: 1;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-7-10 0:44:12
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>